name: "forge"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hdae/stable-diffusion-forge:2025-05-10
    environment:
      - JUPYTER_PASSWORD=jupy73r
    ports:
      - 7860:7860
      - 8888:8888
    volumes:
      - workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  workspace:
