FROM runpod/pytorch:2.8.0-py3.11-cuda12.8.1-cudnn-devel-ubuntu22.04@sha256:cb154fcca15d1d6ce858cfa672b76505e30861ef981d28ec94bd44168767d853

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ARG FORGE_COMMIT_HASH=0ced1d0cd000a536ebd21dc2c8e8636c9104568d
ARG UID=1000

COPY --from=ghcr.io/astral-sh/uv:0.7.3 /uv /uvx /bin/

RUN : Setup environment \
    && mkdir /data \
    && adduser --disabled-password --gecos "" --home "/data/runner" --shell "/bin/bash" --uid "${UID}" runner \
    && apt-get update \
    && apt-get install \
    --yes \
    wget \
    git \
    gosu \
    rsync \
    bc \
    libgl1 \
    libglib2.0-0 \
    libgoogle-perftools-dev \
    && rm -rf /var/lib/apt/lists/* \
    && : Clone repository \
    && mkdir /data/workspace \
    && cd /data/workspace \
    && git init \
    && git remote add origin https://github.com/lllyasviel/stable-diffusion-webui-forge \
    && git fetch --depth 1 origin "${FORGE_COMMIT_HASH}" \
    && git checkout FETCH_HEAD \
    && : Install dependencies \
    # && uv pip install --system --no-cache-dir --pre torch torchvision --index-url https://download.pytorch.org/whl/cu128 \
    # && uv pip install --system --no-cache-dir -r requirements_versions.txt notebook honcho triton==3.3.0 \
    && uv pip install --system --no-cache-dir -r requirements_versions.txt notebook honcho \
    && : Rewrite permission \
    && chown -R runner:runner /data

USER root
WORKDIR /workspace

COPY ./entrypoint.sh /
COPY ./download.sh /
COPY ./Procfile /data/workspace

RUN touch /jupyter.log && chown runner:runner /jupyter.log

EXPOSE 7860
EXPOSE 8888

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "honcho", "start" ]
